<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>SGH SERVICIO</AssemblyName>
    <AssemblyTitle>Sistema Gestor de Hardware</AssemblyTitle>
    <Description>Sistema Gestor de Hardware</Description>
    <Company>IMSS</Company>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    <NoWarn>IL2026;IL2104</NoWarn>
    <Version>1.0.7</Version>
    <AssemblyVersion>1.0.7</AssemblyVersion>
    <FileVersion>1.0.7</FileVersion>
    <!-- Omitir basura web y debug -->
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateStaticWebAssets>false</GenerateStaticWebAssets>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="trimmer-roots.xml" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.9" />
    <PackageReference Include="System.DirectoryServices" Version="10.0.9" />
    <PackageReference Include="System.Management" Version="10.0.3" />
  </ItemGroup>

</Project>